Update libp2p to v0.0.2
soramitsu/soramitsu-hunter pull request #19
Opened 2021-01-28 11:32 UTC by Harrm

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

---

---

2021-01-28 11:54 UTC, igor-egorov requested changes

2021-01-28 11:54 UTC, igor-egorov commented on cmake/projects/libp2p/hunter.cmake
> +    6501ce6cae5309a5597891b44d75de3ebabaf99e
197bf8a8ed89b2cbdc5ccbdc8ec01be23ee5d2f7

2021-01-28 11:55 UTC, igor-egorov commented on cmake/projects/libp2p/hunter.cmake
> +    6501ce6cae5309a5597891b44d75de3ebabaf99e
https://emn178.github.io/online-tools/sha1_checksum.html

2021-01-28 12:04 UTC, xDimon commented on cmake/projects/libp2p/hunter.cmake
> +    6501ce6cae5309a5597891b44d75de3ebabaf99e
```shell
Mi[15:03]~> wget -q https://github.com/soramitsu/cpp-libp2p/archive/v0.0.2.tar.gz
Mi[15:03]~> sha1sum v0.0.2.tar.gz 
197bf8a8ed89b2cbdc5ccbdc8ec01be23ee5d2f7  v0.0.2.tar.gz
```

2021-01-28 12:05 UTC, xDimon requested changes

2021-01-28 12:05 UTC, xDimon commented on cmake/projects/libp2p/hunter.cmake
> +    6501ce6cae5309a5597891b44d75de3ebabaf99e
```suggestion
    197bf8a8ed89b2cbdc5ccbdc8ec01be23ee5d2f7
```

2021-01-28 15:41 UTC, xDimon approved these changes

2021-01-29 09:00 UTC, igor-egorov approved these changes

2021-01-29 09:02 UTC, merged