Feature/libsecp256k1
soramitsu/soramitsu-hunter pull request #20
Opened 2021-01-28 11:43 UTC by Harrm

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

---

2021-01-28 11:52 UTC, igor-egorov requested changes

2021-01-28 11:52 UTC, igor-egorov commented on cmake/projects/libsecp256k1/hunter.cmake
> +    0.1
Version mismatch with default.cmake.
It should be the same in both places - either 0.0.1 or 0.1

2021-01-28 11:53 UTC, igor-egorov commented on cmake/projects/libsecp256k1/hunter.cmake
> +    0.1
It looks like 0.1 is the correct option

2021-01-29 09:00 UTC, igor-egorov approved these changes

2021-01-29 09:07 UTC, xDimon approved these changes

2021-01-29 09:36 UTC, merged